---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/ottodetki/Documents/GitHub/test/Udemy/stack'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _push, symObjAddr: 0x0, symBinAddr: 0x100003D44, symSize: 0x70 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _push, symObjAddr: 0x0, symBinAddr: 0x100003D44, symSize: 0x70 }
  - { offsetInCU: 0x73, offset: 0x73, size: 0x8, addend: 0x0, symName: _pop, symObjAddr: 0x70, symBinAddr: 0x100003DB4, symSize: 0x80 }
  - { offsetInCU: 0xA9, offset: 0xA9, size: 0x8, addend: 0x0, symName: _init, symObjAddr: 0xF0, symBinAddr: 0x100003E34, symSize: 0x1C }
  - { offsetInCU: 0xCD, offset: 0xCD, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x10C, symBinAddr: 0x100003E50, symSize: 0xF8 }
...
